# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89542b54e89498953359b77aba1d56e49331f2ea7738df68858638b1a521959db74cab332af9c622ee08526af0aad1d1122a087ef202d69520dee78e09934f1b

test:
  secret_key_base: 6762d779bdaf183d290cddb9fe475660ec1064c8dc4d2a709c71e229ad57e3359b16e6e3ccaeab9d31f2c25b2615d369a9ae1772dbd610d40e128e6e6ef5f069

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
